<?php
namespace App\Http\Controllers;
use App\Models\SubscriptionPlan;
use Illuminate\Http\Request;
class PageController extends Controller
{
    public function pricing() { $plans = SubscriptionPlan::where("is_active",true)->orderBy("sort_order")->get(); return view("pages.pricing", compact("plans")); }
    public function about()   { return view("pages.about"); }
    public function contact() { return view("pages.contact"); }
    public function faq()     { return view("pages.faq"); }
    public function terms()   { return view("pages.terms"); }
    public function privacy() { return view("pages.privacy"); }
    public function contactSubmit(Request $request) { $request->validate(["name"=>"required","email"=>"required|email","message"=>"required"]); return back()->with("success","Message sent! We will get back to you soon."); }
    public function blog() { $posts = $this->getBlogPosts(); return view("pages.blog.index", compact("posts")); }
    public function blogPost(string $slug) { $posts = $this->getBlogPosts(); $post = collect($posts)->firstWhere("slug", $slug); abort_if(!$post, 404); $related = collect($posts)->where("slug","!=",$slug)->take(3)->values(); return view("pages.blog.show", compact("post","related")); }
    private function getBlogPosts(): array { return [
        ["slug"=>"buying-a-used-car-in-kenya-complete-guide","title"=>"Buying a Used Car in Kenya: The Complete 2026 Guide","excerpt"=>"From checking logbooks to understanding import duty - everything you need to know before buying your next car in Kenya.","body"=>"<p>Buying a used car in Kenya can be both exciting and stressful. With fraud commonplace on informal platforms, you need a trusted guide.</p><h4>1. Check the Logbook</h4><p>The logbook is the most important document. Verify the chassis number matches the car. Confirm seller name matches their ID. Check for outstanding loans.</p><h4>2. Inspect the Car</h4><p>Always have an independent mechanic inspect before purchase. Check for accident repairs, test the engine cold, test all electrics and AC.</p><h4>3. Verify at NTSA</h4><p>Use ntsa.go.ke to verify vehicle ownership and check for encumbrances. This takes minutes and can save you from massive losses.</p><h4>4. Use AutoScore</h4><p>Every AutoVault listing has an AutoScore that factors price competitiveness, seller history, and listing completeness. Score 80+ means a solid deal.</p>","author"=>"AutoVault Team","category"=>"Buying Guide","date"=>"March 2026","image"=>"assets/images/blog/blog-15.jpg"],
        ["slug"=>"top-5-suvs-under-3-million-kenya-2026","title"=>"Top 5 SUVs Under KES 3 Million in Kenya 2026","excerpt"=>"We ranked the best SUVs you can buy for under KES 3M in Kenya - Toyota, Nissan, Subaru and more compared side by side.","body"=>"<p>SUVs dominate Kenyan roads. Here are the top 5 you can get for under KES 3 million.</p><h4>1. Toyota RAV4 (2010-2014)</h4><p>The go-to family SUV. Reliable, spares everywhere. Expect KES 1.8M-2.5M for a clean unit.</p><h4>2. Nissan X-Trail (2007-2013)</h4><p>Spacious, 4WD capable and affordable. Available from KES 1.2M. Watch out for CVT issues on older models.</p><h4>3. Subaru Forester (2008-2013)</h4><p>AWD handles Kenyan roads beautifully. Budget KES 1.5M-2.2M.</p><h4>4. Honda CR-V (2007-2012)</h4><p>Comfortable, fuel-efficient for an SUV. KES 1.4M-2.0M. Parts widely available.</p><h4>5. Toyota Harrier (2003-2013)</h4><p>Premium look at accessible price. Budget KES 1.8M-2.8M.</p>","author"=>"AutoVault Team","category"=>"Top Lists","date"=>"February 2026","image"=>"assets/images/blog/blog-16.jpg"],
        ["slug"=>"how-to-import-a-car-from-japan-to-kenya","title"=>"How to Import a Car from Japan to Kenya in 2026","excerpt"=>"Step-by-step guide to importing a car from Japan - from auction houses to clearing at Mombasa port.","body"=>"<p>Japan remains the top source of quality used cars. Kenya imports thousands every year.</p><h4>Step 1: Choose an Auction Agent</h4><p>Use a reputable Kenya-registered agent who bids at Japanese auctions (USS, TAA, JAA). Budget USD 200-500 for agent fees.</p><h4>Step 2: Understand Auction Grades</h4><p>Grade 4 and above means excellent condition. Grade 3 is good with minor issues. Avoid grade 2 and below.</p><h4>Step 3: Calculate Total Cost</h4><p>Auction price + freight (USD 800-1,200) + insurance + Kenya import duty 25% + IDF 2.25% + CRSP 7% + VAT 16%.</p><h4>Step 4: Clear at Mombasa</h4><p>Your agent handles most paperwork. Clearance takes 3-10 days after vessel arrives.</p>","author"=>"AutoVault Team","category"=>"Import Guide","date"=>"January 2026","image"=>"assets/images/blog/blog-17.jpg"],
        ["slug"=>"what-is-autoscore-how-it-protects-buyers","title"=>"What is AutoScore and How Does It Protect Car Buyers?","excerpt"=>"AutoScore is Kenya first car listing trust index. Here exactly how we calculate it and why it matters.","body"=>"<p>AutoVault AutoScore is a 0-100 trust rating assigned to every car listing. It instantly tells buyers whether a listing is trustworthy and fairly priced.</p><h4>What Goes Into AutoScore?</h4><p>Our algorithm weighs: Seller verification (20pts), listing completeness - photos, description, specs (25pts), price vs market comps (30pts), seller response rate (15pts), listing activity (10pts).</p><h4>Score Meanings</h4><p><strong>90-100 Excellent:</strong> Verified seller, competitive price. Proceed with confidence. <strong>70-89 Good:</strong> Solid listing. <strong>50-69 Fair:</strong> Needs due diligence. <strong>Below 50:</strong> Approach with caution.</p><h4>Why It Matters in Kenya</h4><p>Kenya informal car market has inflated prices and misleading listings. AutoScore cuts through and gives buyers an instant, data-driven quality signal.</p>","author"=>"AutoVault Team","category"=>"Features","date"=>"March 2026","image"=>"assets/images/blog/blog-18.jpg"],
    ]; }
}
