@extends('layouts.app')
@section('title', 'Contact AutoVault')
@section('content')
<section class="flat-title"><div class="container2"><div class="row"><div class="col-lg-12"><div class="title-inner style"><div class="title-group fs-12"><a class="home fw-6 text-color-3" href="{{ route('home') }}" wire:navigate>Home</a><span>Contact us</span></div></div></div></div></div></section>
<section class="flat-property"><div class="container"><div class="row"><div class="col-lg-12"><div class="inner-heading flex-two flex-wrap"><h1 class="heading-listing">Contact us</h1><div class="social-listing flex-six flex-wrap"><p>Share this page:</p><div class="icon-social style1"><a href="#"><i class="icon-autodeal-facebook"></i></a><a href="#"><i class="icon-autodeal-linkedin"></i></a><a href="#"><i class="icon-autodeal-twitter"></i></a><a href="#"><i class="icon-autodeal-instagram"></i></a></div></div></div></div></div></div></section>
<section class="tf-section-map"><div class="container-fluid"><div class="map"><iframe class="map-content" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15955.048127780764!2d36.81947!3d-1.286389!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x182f10d4fd9e5c47%3A0x85e1b5b2d81f1d87!2sNairobi%20CBD!5e0!3m2!1sen!2ske!4v1710000000000!5m2!1sen!2ske" allowfullscreen="" loading="lazy"></iframe></div></div></section>
<section class="tf-section-contact"><div class="container"><div class="row"><div class="col-md-8 contact-left"><div class="heading-section mb-30"><h2>Drop Us a Line</h2><p class="mt-12">Feel free to connect with us through our online channels for updates, news, and more.</p></div><div id="comments" class="comments"><div class="respond-comment"><form method="post" class="comment-form form-submit" action="{{ route('contact.submit') }}">@csrf<div class="grid-sw-2"><fieldset class="email-wrap style-text"><label class="font-1 fs-14 fw-5">Name</label><input type="text" class="tb-my-input" name="name" placeholder="Your name" required></fieldset><fieldset class="phone-wrap style-text"><label class="font-1 fs-14 fw-5">Email address</label><input type="email" class="tb-my-input" name="email" placeholder="Your email" required></fieldset></div><div class="grid-sw-2"><fieldset class="email-wrap style-text"><label class="font-1 fs-14 fw-5">Phone Number</label><input type="tel" class="tb-my-input" name="phone" placeholder="+254 700 000 000" required></fieldset><fieldset class="phone-wrap style-text"><label class="font-1 fs-14 fw-5">Subject</label><input type="text" class="tb-my-input" name="subject" placeholder="Enter subject" required></fieldset></div><fieldset class="phone-wrap style-text"><label class="font-1 fs-14 fw-5">Your Message</label><textarea name="message" rows="4" placeholder="Your message" aria-required="true"></textarea></fieldset><div class="button-boxs"><button class="sc-button" name="submit" type="submit"><span>Send Message</span></button></div></form></div></div></div><div class="col-md-4 contact-right"><div class="contact-info box-sd"><h2 class="mb-30">Contact Us</h2><div class="wrap-info"><div class="box-info"><h5>Address</h5><p>AutoVault Kenya<br>Westlands, Nairobi, Kenya</p></div><div class="box-info"><h5>Information:</h5><p>+254 700 100 200</p><p>hello@autovault.co.ke</p></div><div class="box-info"><h5>Open Hours:</h5><p>Monday - Friday: 08:00 - 18:00</p><p>Saturday: 09:00 - 14:00</p></div><div class="box-info"><h5>Follow Us:</h5><div class="icon-social style2"><a href="#"><i class="icon-autodeal-facebook"></i></a><a href="#"><i class="icon-autodeal-linkedin"></i></a><a href="#"><i class="icon-autodeal-twitter"></i></a><a href="#"><i class="icon-autodeal-instagram"></i></a></div></div></div></div></div></div></div></section>
<section class="flat-brand tf-section3"><div class="container"><div class="row"><div class="col-lg-12"><div class="title-section center"><h2>Our Partners</h2></div><div dir="ltr" class="swiper-container carousel-5"><div class="swiper-wrapper"><div class="swiper-slide"><div class="slogan-logo"><a href="#"><img src="{{ asset('assets/images/partner/par1.png') }}" alt="Partner"></a></div></div><div class="swiper-slide"><div class="slogan-logo"><a href="#"><img src="{{ asset('assets/images/partner/par2.png') }}" alt="Partner"></a></div></div><div class="swiper-slide"><div class="slogan-logo"><a href="#"><img src="{{ asset('assets/images/partner/par3.png') }}" alt="Partner"></a></div></div><div class="swiper-slide"><div class="slogan-logo"><a href="#"><img src="{{ asset('assets/images/partner/par4.png') }}" alt="Partner"></a></div></div><div class="swiper-slide"><div class="slogan-logo"><a href="#"><img src="{{ asset('assets/images/partner/par5.png') }}" alt="Partner"></a></div></div><div class="swiper-slide"><div class="slogan-logo"><a href="#"><img src="{{ asset('assets/images/partner/par6.png') }}" alt="Partner"></a></div></div></div></div></div></div></div></section>

@endsection
